### ISSUE TITLE
Add atomic radii?

### ISSUE THREAD

**Issue by rsdefever** [rsdefever/element#10]
I would be OK adding this data at a later point, after an initial release.

**Comment by daico007** [comment]
Yeah, it make sense to have these info as it is a standalone package. I think the next step would be finding a way to scrape these info from some NIST or some reliable source.

**Comment by daico007** [comment]
Tagging along, I think density info may also be helpful to have (like for `mbuild` `fill_box` function)

**Comment by rsdefever** [comment]
> Yeah, it make sense to have these info as it is a standalone package. I think the next step would be finding a way to scrape these info from some NIST or some reliable source.

It should come from NIST. Scraping is best but it may require some by-hand curation as did the mass data. Its not impossible for ~100 elements.

> Tagging along, I think density info may also be helpful to have (like for mbuild `fill_box` function)

I disagree here, the density is not an elemental property, unless you are thinking of an atomic fluid, e.g., argon. Even then density is normally provided to `fill_box`.

**Comment by daico007** [comment]
Yup, that's true, I take back that suggestion.

**Comment by jennyfothergill** [comment]
I'm finally peeking at this package and it is _clean_! 🤩 This might be a good source for empirical atomic radii https://doi.org/10.1063/1.1725697. Or if we want van der Waal's radii, this might be good https://doi.org/10.1039/C3DT50599E. I'd be happy to add either/both in a PR if you like.

**Comment by rsdefever** [comment]
@jennyfothergill why do you suggest those sources? I'm not in opposition, I just don't know what would be considered the "gold-standard" data. It's all pretty far out of my area of expertise.

IMO, we only need one set of radii, so I would probably vote for the van der Waals radii. But I would be opening to listening others think we should have more (it looks like `QCElemental` supports covalent radii and van der Waals radii).

**Comment by jennyfothergill** [comment]
@rsdefever I couldn't find a NIST source for atomic radii--I think because there's a lot of variation depending on which radius you consider (VDW, ionic, covalent). I am open to a different source--I just thought those might be useful. :)

**Comment by rsdefever** [comment]
@jennyfothergill no I definitely appreciate the suggestions!! The main questions I'm trying to answer for myself are:
* do we need some sort of radii in this package?
* what is the benefit/what will it be used for?
* do the answers to the prior two questions inform what radii should be included?

All open ended. I don't have coherent answers for any of them yet.

**Comment by bdice** [comment]
If the previous questions (on necessity and usage) are answered, here are some further thoughts. 😉

I recommend naming the property in a way that indicates the definition used (e.g. "van der Waals radius" and not just "radius"). There are some notes about measuring/calculating atomic radii on [this Wikipedia data page](https://en.wikipedia.org/wiki/Atomic_radii_of_the_elements_(data_page)) that may be helpful disclaimers to include in the docs, in addition to listing whatever sources of data are used. 

Here are some notes on how other periodic table packages solve this problem:

### mendeleev
https://mendeleev.readthedocs.io/en/stable/code.html#element
- Includes many properties based on the source, such as `atomic_radius`, `atomic_radius_rahm`, `covalent_radius_bragg`, `covalent_radius_cordero`, `covalent_radius_pyykko`, etc.

### periodictable
https://periodictable.readthedocs.io/en/latest/api/covalent_radius.html
- Uses Cordero for radius (`covalent_radius` property), also includes uncertainty 🤷 (`covalent_radius_uncertainty` property) and units.
- It documents that the `covalent_radius` is the "average atomic radius when bonded to C, N or O."
- It mentions that the CRC uses the average of Cordero and Pyykkö.

**Comment by justinGilmer** [comment]
I think having some radii property would be excellent (can enable new visualization backends possibly). 

I echo what Bradley said above, as long as the radius term is specifically named and sources are available for the radii and method If necessary.

**Comment by bdice** [comment]
Visualization might already be solved, since most software for that kind of thing also has to know the usual [CPK coloring](https://en.wikipedia.org/wiki/CPK_coloring). I assume that radii are already included in packages supporting CPK or similar colors. 😄

**Comment by mikemhenry** [comment]
+1 to naming what the "radius" actually is, the radius of an atom is very poorly defined.

**Comment by rsdefever** [comment]
Given that the MoSDeF focus is primarily soft matter systems, I think the van der Waals radii probably make the most sense. [This]( https://doi.org/10.1039/C3DT50599E) reference (thanks to @jennyfothergill) seems good, and has vdW radii up to atomic number 100.

I've also finally found a good reason to add these; they might be needed for my partial charge module.

**Comment by rsdefever** [comment]
@jennyfothergill did you want to take the lead on this? If not, thats fine, but I want to get this added reasonably soon, so I'll go ahead and do it :).
