### ISSUE TITLE
Verify no elements have same mass

### ISSUE THREAD

**Issue by rsdefever** [rsdefever/element#16]
If any elements have the same mass, the output of the element_from_mass function may have ill-defined output.

**Comment by rsdefever** [comment]
Some of the elements do have the same mass. These come from the high atomic number cases where the mass is defined as the mass number of the most stable isotope. We need to consider how we want to handle these situations. This is an edge case, most elements that will be commonly used do not suffer from this problem.

@umesh-timalsina any ideas?

**Comment by umesh-timalsina** [comment]
Couple of ideas,
1. Return all the matching elements preferably as a tuple/list depending on the use case.
2. Raise an error `DuplicateElementError` or `MultiMatchError`. Can have a flag like `silent=True` for suppressing this error.

**Comment by rsdefever** [comment]
I prefer 2; it will only be a problem with `element_from_mass`; in these few (5, I think) cases there is not a unique choice. We also need to ensure the `exact=False` behavior is correct. We can use a `return_duplicates=True` flag if the user wishes to return duplicates; it should return a tuple of elements in that case.

**Comment by daico007** [comment]
I agree default to raising error when there is no unique match when searching with mass is the better option. And if the user choose to ignore the error, beside the option of returning a tuple of matched element, I think we also have the option of just return `None` along with a warning message indicating the index of the Atom (so they can select it later) and the matched list. That way, the user can go back add the missing ones manually.

**Comment by rsdefever** [comment]
> I agree default to raising error when there is no unique match when searching with mass is the better option. And if the user choose to ignore the error, beside the option of returning a tuple of matched element, I think we also have the option of just return `None` along with a warning message.

This is OK with me, instead of `return_duplicates=bool` we can use an `enum` with options `duplicates="error"`, `duplicates="all"`, or `duplicates="none"`.

>  indicating the index of the Atom (so they can select it later) and the matched list.

I think this is behavior that would be in the external package `gmso`, `mbuild`, `foyer`, etc, rather than here. `ele` has no knowledge of atom or atom indicies.
