### ISSUE TITLE
Considering exporting immutable structures

### ISSUE THREAD

**Issue by umesh-timalsina** [rsdefever/element#18]
```py

>>> from ele.element import element_from_symbol
>>> element_from_symbol('O')
Element: oxygen, symbol: O, atomic number: 8, mass: 15.999
>>> from ele.element import symbol_dict
>>> symbol_dict.clear()  # This should not be allowed
>>> element_from_symbol('O')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/umesh/work/mosdef-hub/contrib/element/ele/element.py", line 65, in element_from_symbol
    raise ElementError(f"No element with symbol {symbol}")
ele.exceptions.ElementError: No element with symbol O

```

**Comment by rsdefever** [comment]
I agree. What is the best way to do this?

**Comment by daico007** [comment]
I don't think there is a built-in immutable dict data structure for python, but there are a few workaround for that: 
1. Build ourselves a simple FrozenDict class to store these info (https://stackoverflow.com/questions/11014262/how-to-create-an-immutable-dictionary-in-python)
2. Use frozenset to store the info and convert it back to dict to use for other functions (https://stackoverflow.com/questions/39440190/a-workaround-for-pythons-missing-frozen-dict-type)

**Comment by rsdefever** [comment]
There is also this here: https://github.com/slezica/python-frozendict/blob/master/frozendict/__init__.py

Another question @umesh-timalsina. Is this something we need to worry about? The user shouldn't be touching the `symbol_dict` anyway. They should only interface with `ele` through `element _from_symbol`, `element_from_mass`, `element_from_atomic_number` or `Elements.X`.

**Comment by umesh-timalsina** [comment]
Yeah, we shouldn't worry about that. To make package full proof, it might be nice to add a `__all__` dunder to element.py.
