### ISSUE TITLE
Add a script to reproduce the json file

### ISSUE THREAD

**Issue by uppittu11** [rsdefever/element#19]
It could be useful to include the script you used to generate the json file from the downloaded NIST table. That way it would be easy to reproduce it in the future if we change formats or need to add in new elements. Especially if we use a file format that isn't very human-readable (like in #4)

If you don't want that script in the conda package you could make a new folder in the home directory and put it there. Then it will be on GitHub but not a part of the conda or pypi packages.

**Comment by rsdefever** [comment]
@uppittu11 sadly I did not use a script. It was built by hand. The list of caveats [here](https://github.com/rsdefever/ele/blob/master/ele/lib/README.md) makes it hard to write a script to grab the data.
